### ISSUE TITLE
Request To Add Product in Start Svelte

### ISSUE THREAD

**Issue by maheshwari-1153** [blacksonic/todomvc-svelte#1]
Hello,

I am Maheshwari Shukla from the [GeekyAnts](https://geekyants.com/) team. 

On behalf of [Start Svelte](http://startsvelte.com/), we add open-source products that we find helpful to the community & also we provide credits to the author itself.

Let me know if you are interested to showcase your product in our open-source website.

If yes, then I request you to add MIT Licence & screenshots of your template in your repo.

Looking forward to hearing from you.

**Comment by blacksonic** [comment]
Hi,

Thanks for reaching out!
I'm interested indeed and I've already added the MIT license and a screenshot to the project.

**Comment by maheshwari-1153** [comment]
Thanks for getting back quickly. 

If possible, can you please add 2-3 more screenshots?

**Comment by blacksonic** [comment]
I feel everything is on this one screenshot...what should I add also?

**Comment by maheshwari-1153** [comment]
I understand, no problem. I will share the link with you once the product is added.

**Comment by maheshwari-1153** [comment]
You can check your UI here: http://startsvelte.com/themes/svelte-todo-app/ 

Do let me know your thoughts regarding the same.
